### ISSUE TITLE
key error 'cjdata'

### ISSUE THREAD

**Issue by francismontalbo** [guillaumefrd/brain-tumor-mri-dataset#2]
Hello, I'm getting an error when the images are being loaded.

'Key error cjdata'

**Comment by francismontalbo** [comment]
brain_tumor_dataset\brain-tumor-mri-dataset-master\matlab_to_numpy.py", line 57, in <module>
    mat_file = hdf5storage.loadmat(os.path.join(data_dir, file))['cjdata'][0]
KeyError: 'cjdata'

**Comment by francismontalbo** [comment]
I managed to fix it. This is closed.

**Comment by MariaSA2023** [comment]
Can you plz tell me how you solved the problem?
I downloaded the BSDS from [The Berkeley Segmentation Dataset and Benchmark](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds/) data and I need to convert the ground truth images from . mat to .jpg; I tried this code [Converting .mat file extension image to .jpg via python](https://stackoverflow.com/questions/59208896/converting-mat-file-extension-image-to-jpg-via-python) proposed by

Mr.Rotem

but it doesn't work for me, I got this error: KeyError: 'cjdata' I couldn't fix it, I also tried online converters without any avail any help to convert these images
